language: node_js
node_js: 
  - '14'

addons:
  chrome: stable
  apt:
    packages:
      - "python3"
      - "python3-pip"

cache: npm

script:
  - pip3 -V
  - npm run lint
  - npm run test
  - npm run e2e
  - npm run build